### PR TITLE
Linters, Html,Css

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
Added Webhint and Stylelint linters to the root directory
Added readme file to the project
Added Html and linked CSS

### CODE REVIEW

**Comment by sharon-odhiambo** [comment]
Hello, I just made the required changes. Kindly check and let me know whether it's ready to merge now.

**Comment by sharon-odhiambo** [comment]
Hello @chaw-bot , I just made the required changes. Kindly check and let me know whether it's ready to merge now.

**Review by topeogunleye — CHANGES_REQUESTED** [review]
> # Changes Required 
> ### Hi @sharon-odhiambo,
> Nice job, you are almost there.
> 
> 
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
>- [ ] kindly remove your `node_modules` folder from your `project-feature` GitHub branch as you may have mistakenly pushed  `node_modules` to your branch repo.
>- [ ] As the previous code reviewer suggested, please kindly set up linters, and ensure there are no linter errors when you submit for rereview. Here is a demo video below for setting up linters:

https://user-images.githubusercontent.com/52934128/170314202-979f2396-b1e2-409f-abd8-ba2491050667.mp4


> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by omarsalem7 — APPROVED** [review]
Hi @sharon-odhiambo , 
# STATUS: APPROVED! 🥇 💯 
giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Descriptive pull request ✔️
- Good descriptive readme ✔️
- No linter errors ✔️

Cheers and Happy coding!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Code Review by @omarsalem7

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
